# -*- coding: utf-8 -*-
"""Restitution de l'accentuation sur la couche editoriale.
Outil de redaction, execute une fois. Conserve dans le depot pour memoire."""
import json, re, sys, pathlib

MOTS = {
"Age":"Âge","Ameliorer":"Améliorer","Budgetiser":"Budgétiser","Caiman":"Caïman","Ceder":"Céder",
"Comite":"Comité","Communautes":"Communautés","Creer":"Créer","Declencheur":"Déclencheur",
"Defendable":"Défendable","Depense":"Dépense","Deplacer":"Déplacer","Deplafonner":"Déplafonner",
"Economie":"Économie","Economies":"Économies","Elargir":"Élargir","Engages":"Engagés","Etaler":"Étaler",
"Evaluation":"Évaluation","Evaluer":"Évaluer","Meme":"Même","Methodologie":"Méthodologie",
"Negocier":"Négocier","Perequation":"Péréquation","Portee":"Portée","Precedent":"Précédent",
"Prevenir":"Prévenir","Prevoir":"Prévoir","Prevot":"Prévot","Realisme":"Réalisme","Recoupe":"Recoupe",
"Reduction":"Réduction","Reduire":"Réduire","Reevaluer":"Réévaluer","Refondre":"Refondre",
"Reformateur":"Réformateur","Reforme":"Réforme","Reformer":"Réformer","Regions":"Régions",
"Reintegrer":"Réintégrer","Rendement":"Rendement","Reorienter":"Réorienter","Requalifier":"Requalifier",
"Responsabilisation":"Responsabilisation","Reserve":"Réserve","Resserrer":"Resserrer",
"Revoir":"Revoir","Revues":"Revues","Sanctionne":"Sanctionné","Sante":"Santé","Sincerite":"Sincérité",
"Supprimer":"Supprimer","Transferer":"Transférer","Reprendre":"Reprendre","Relever":"Relever",
"abus":"abus","accelerees":"accélérées","adosse":"adossé","adossee":"adossée","affiche":"affiché",
"affichee":"affichée","affiches":"affichés","agences":"agences","ameliore":"améliore","annee":"année",
"annonce":"annonce","annoncee":"annoncée","ante":"ante","apaise":"apaise","apres":"après",
"assainissements":"assainissements","assiette":"assiette","assortie":"assortie","assorti":"assorti",
"assume":"assume","assumee":"assumée","atteint":"atteint","attendue":"attendue","aujourd'hui":"aujourd'hui",
"bareme":"barème","budgetaire":"budgétaire","budgetaires":"budgétaires","caducite":"caducité",
"calibre":"calibré","capacite":"capacité","capitalisation":"capitalisation","caractere":"caractère",
"categorie":"catégorie","cede":"cédé","ceder":"céder","celle":"celle","cellules":"cellules",
"centaines":"centaines","cheques":"chèques","chiffrable":"chiffrable","chomage":"chômage",
"cible":"ciblé","ciblee":"ciblée","ciblees":"ciblées","cinglant":"cinglant","civile":"civile",
"comite":"comité","compense":"compensé","competence":"compétence","complete":"complète",
"comportement":"comportement","comptabilise":"comptabilisé","comptabiliser":"comptabiliser",
"concentre":"concentré","concerne":"concerné","concernes":"concernés","conciliation":"conciliation",
"conditions":"conditions","confie":"confie","conjoncturelle":"conjoncturelle","connue":"connue",
"considerable":"considérable","consolide":"consolidé","consolidee":"consolidée","conteste":"contesté",
"contradiction":"contradiction","contrepartie":"contrepartie","contribuables":"contribuables",
"controle":"contrôle","cooperation":"coopération","correction":"correction","corrections":"corrections",
"corrige":"corrigé","cotisation":"cotisation","cotisations":"cotisations","coupes":"coupes",
"courantes":"courantes","cout":"coût","coute":"coûte","couter":"coûter","couts":"coûts",
"creation":"création","credibilite":"crédibilité","credible":"crédible","credit":"crédit",
"credits":"crédits","creuser":"creuser","critique":"critique","cumule":"cumulé","cycle":"cycle",
"cyclique":"cyclique","debattus":"débattus","decale":"décale","decide":"décide","decideurs":"décideurs",
"decisif":"décisif","declaree":"déclarée","declenche":"déclenche","decote":"décote","decoule":"découle",
"decoupler":"découpler","decroissants":"décroissants","deduction":"déduction","defendre":"défendre",
"defendue":"défendue","defense":"défense","definitivement":"définitivement","degage":"dégage",
"degrade":"dégrade","degressive":"dégressive","deja":"déjà","dela":"delà","delai":"délai",
"demandeurs":"demandeurs","demi":"demi","demontre":"démontré","depassement":"dépassement",
"depend":"dépend","dependant":"dépendant","depense":"dépense","depenses":"dépenses",
"derogatoires":"dérogatoires","desendettement":"désendettement","desormais":"désormais",
"destruction":"destruction","dette":"dette","developpement":"développement","devrait":"devrait",
"diesel":"diesel","difference":"différence","differes":"différés","diffus":"diffus",
"digitalisation":"digitalisation","diplomatique":"diplomatique","directe":"directe","directs":"directs",
"disparaissent":"disparaissent","dispositif":"dispositif","distributif":"distributif","dixiemes":"dixièmes",
"documentait":"documentait","documente":"documenté","documentee":"documentée","documentees":"documentées",
"dotation":"dotation","dotations":"dotations","douane":"douane","douzieme":"douzième",
"droits":"droits","durablement":"durablement","duree":"durée","dysfonctionnel":"dysfonctionnel",
"ecart":"écart","ecarter":"écarter","echeant":"échéant","echec":"échec","eco":"éco",
"ecofiscalite":"écofiscalité","economies":"économies","economique":"économique","economiques":"économiques",
"editorial":"éditorial","effectif":"effectif","effectifs":"effectifs","effective":"effective",
"effectivite":"effectivité","efficacite":"efficacité","efficience":"efficience","electoral":"électoral",
"electorat":"électorat","electronique":"électronique","eleve":"élevé","elevee":"élevée","elevees":"élevées",
"endotheliales":"endothéliales","energies":"énergies","entiere":"entière","entierement":"entièrement",
"entite":"entité","entree":"entrée","entrees":"entrées","equitables":"équitables","equivalente":"équivalente",
"equivalents":"équivalents","er":"er","esperance":"espérance","etablisse":"établisse","etalee":"étalée",
"etant":"étant","ete":"été","etendu":"étendu","etre":"être","etroite":"étroite","europeenne":"européenne",
"evaluee":"évaluée","eventuelle":"éventuelle","evite":"évité","exclus":"exclus","exemptee":"exemptée",
"exercices":"exercices","exige":"exige","exiger":"exiger","exigerait":"exigerait","existant":"existant",
"existante":"existante","exonerations":"exonérations","experience":"expérience","explicite":"explicite",
"explicitee":"explicitée","explosif":"explosif","expose":"exposé","extinction":"extinction",
"facture":"facture","faiblesse":"faiblesse","faisabilite":"faisabilité","familiales":"familiales",
"federal":"fédéral","federale":"fédérale","federales":"fédérales","federaux":"fédéraux","fevrier":"février",
"finalite":"finalité","financier":"financier","financieres":"financières","financiers":"financiers",
"fiscalite":"fiscalité","fixee":"fixée","fixes":"fixés","flexi":"flexi","fluidifier":"fluidifier",
"fonctionnement":"fonctionnement","fondee":"fondée","forfaitaire":"forfaitaire",
"forfaitairement":"forfaitairement","formulation":"formulation","fourchettes":"fourchettes",
"francaise":"française","franchise":"franchise","fraude":"fraude","frontale":"frontale",
"generale":"générale","generalise":"généralisé","generalisee":"généralisée","gerer":"gérer",
"greve":"grève","hausses":"hausses","hautes":"hautes","hospitalier":"hospitalier","hypotheses":"hypothèses",
"immediat":"immédiat","immediatement":"immédiatement","immobilier":"immobilier","immobiliers":"immobiliers",
"impot":"impôt","imposables":"imposables","improbable":"improbable","incapacite":"incapacité",
"incertain":"incertain","incertitude":"incertitude","incompatible":"incompatible","indemnite":"indemnité",
"indexe":"indexé","industrie":"industrie","initial":"initial","inscrit":"inscrit","instaurer":"instaurer",
"institutionnel":"institutionnel","integral":"intégral","integralement":"intégralement",
"integrant":"intégrant","interdit":"interdit","interet":"intérêt","interlocuteurs":"interlocuteurs",
"international":"international","internationales":"internationales","interprofessionnel":"interprofessionnel",
"intitule":"intitulé","intitules":"intitulés","inverse":"inverse","isole":"isolé","isolee":"isolée",
"janvier":"janvier","jugement":"jugement","juillet":"juillet","juridique":"juridique","juste":"juste",
"justifier":"justifier","legal":"légal","legale":"légale","legislature":"législature","lent":"lent",
"levier":"levier","liberale":"libérale","liberatoire":"libératoire","lie":"lié","lien":"lien","lier":"lier",
"lies":"liés","ligne":"ligne","lignes":"lignes","limitation":"limitation","limiter":"limiter",
"lineaire":"linéaire","locatifs":"locatifs","locaux":"locaux","logement":"logement","logique":"logique",
"loi":"loi","longue":"longue","loyer":"loyer","loyers":"loyers","macrobudgetaires":"macrobudgétaires",
"maitrise":"maîtrise","malades":"malades","maladie":"maladie","malus":"malus","maniere":"manière",
"manoeuvre":"manœuvre","manquement":"manquement","marches":"marchés","marge":"marge","mars":"mars",
"massive":"massive","matiere":"matière","mecaniquement":"mécaniquement","mediateur":"médiateur",
"medicaux":"médicaux","meilleur":"meilleur","meilleure":"meilleure","meme":"même","mesure":"mesure",
"mesures":"mesures","methode":"méthode","methodologie":"méthodologie","migratoire":"migratoire",
"migratoires":"migratoires","migrent":"migrent","militaires":"militaires","millionnaires":"millionnaires",
"ministre":"ministre","ministres":"ministres","mobilier":"mobilier","mobiliers":"mobiliers",
"mobilite":"mobilité","modalites":"modalités","modele":"modèle","modelisee":"modélisée",
"moderateur":"modérateur","modeste":"modeste","monde":"monde","monitoring":"monitoring","montant":"montant",
"moyen":"moyen","moyenne":"moyenne","moyennes":"moyennes","moyens":"moyens","naif":"naïf",
"nationale":"nationale","nature":"nature","necessaire":"nécessaire","neerlandais":"néerlandais",
"neerlandaise":"néerlandaise","negatif":"négatif","negligeable":"négligeable","negociation":"négociation",
"negociations":"négociations","neige":"neige","nets":"nets","nette":"nette","nettes":"nettes",
"nettoyage":"nettoyage","neutralisent":"neutralisent","neutre":"neutre","niches":"niches","niveau":"niveau",
"niveaux":"niveaux","nommee":"nommée","normal":"normal","norme":"norme","notation":"notation",
"notion":"notion","nourri":"nourri","nouveau":"nouveau","nouvelle":"nouvelle","nouvelles":"nouvelles",
"novembre":"novembre","obligations":"obligations","oeuvre":"œuvre","officiel":"officiel",
"officielle":"officielle","operationnel":"opérationnel","operations":"opérations","optimale":"optimale",
"ordre":"ordre","orientante":"orientante","original":"original","ouvert":"ouvert","ouvrant":"ouvrant",
"parafiscal":"parafiscal","parafiscales":"parafiscales","parlementaires":"parlementaires","parti":"parti",
"participations":"participations","partie":"partie","partielle":"partielle","partiellement":"partiellement",
"partis":"partis","passage":"passage","pathologie":"pathologie","patrimoine":"patrimoine",
"patrimoines":"patrimoines","patrimoniale":"patrimoniale","patrimoniales":"patrimoniales",
"patronale":"patronale","patronales":"patronales","pensee":"pensée","pension":"pension","pensions":"pensions",
"perception":"perception","percu":"perçu","performantes":"performantes","personnel":"personnel",
"personnes":"personnes","physiques":"physiques","piege":"piège","pilier":"pilier","plafond":"plafond",
"plafonne":"plafonné","plafonnee":"plafonnée","plafonner":"plafonner","plein":"plein","pluriannuel":"pluriannuel",
"pluriannuelle":"pluriannuelle","plutot":"plutôt","police":"police","politique":"politique",
"politiquement":"politiquement","populaire":"populaire","population":"population","portant":"portant",
"portees":"portées","poser":"poser","position":"position","possible":"possible","pouvoir":"pouvoir",
"pouvoirs":"pouvoirs","pratique":"pratique","pratiquent":"pratiquent","prealable":"préalable",
"precedents":"précédents","precis":"précis","precompte":"précompte","preference":"préférence",
"presence":"présence","presente":"présenté","presentee":"présentée","prestations":"prestations",
"preuve":"preuve","preuves":"preuves","prevue":"prévue","primaire":"primaire","primaires":"primaires",
"privatisation":"privatisation","probabilite":"probabilité","probleme":"problème","proche":"proche",
"produire":"produire","produit":"produit","professionnel":"professionnel","profonde":"profonde",
"programme":"programme","programmee":"programmée","progressif":"progressif","progressive":"progressive",
"prolonger":"prolonger","propose":"proposé","proposition":"proposition","propres":"propres",
"proprietaires":"propriétaires","provenance":"provenance","provient":"provient","provisoires":"provisoires",
"publics":"publics","publies":"publiés","publique":"publique","publiquement":"publiquement",
"publiques":"publiques","qualifiee":"qualifiée","quarante":"quarante","quotite":"quotité","rabot":"rabot",
"raboter":"raboter","ralentir":"ralentir","rallier":"rallier","ramenant":"ramenant","ramenee":"ramenée",
"rang":"rang","rapide":"rapide","rapport":"rapport","rapportant":"rapportant","rapporte":"rapporte",
"rapportent":"rapportent","rationaliser":"rationaliser","reaction":"réaction","reactions":"réactions",
"realisation":"réalisation","realise":"réalisé","realiste":"réaliste","realistes":"réalistes",
"reapparait":"réapparaît","recette":"recette","recettes":"recettes","recommandations":"recommandations",
"recommande":"recommandé","reconduction":"reconduction","reconversion":"reconversion","recoupe":"recoupe",
"recours":"recours","recouvre":"recouvre","recouvrement":"recouvrement","recuperer":"récupérer",
"redecouvert":"redécouvert","redessiner":"redessiner","reduction":"réduction","reductions":"réductions",
"reduit":"réduit","reduits":"réduits","reel":"réel","reelle":"réelle","reellement":"réellement",
"reels":"réels","reference":"référence","referme":"referme","reforme":"réforme","reformer":"réformer",
"refuser":"refuser","regime":"régime","regimes":"régimes","regionale":"régionale",
"reglementation":"réglementation","regles":"règles","reintegration":"réintégration","relevant":"relevant",
"releve":"relève","relevement":"relèvement","relever":"relever","remboursement":"remboursement",
"remuneration":"rémunération","remunerations":"rémunérations","rend":"rend","rendement":"rendement",
"rendements":"rendements","rendre":"rendre","rentree":"rentrée","reorganisations":"réorganisations",
"reparti":"réparti","repartit":"répartit","repartition":"répartition","repas":"repas","reponse":"réponse",
"report":"report","reporter":"reporter","repose":"repose","representent":"représentent","reserve":"réserve",
"resoudre":"résoudre","ressources":"ressources","restant":"restant","reste":"reste","resultats":"résultats",
"retenir":"retenir","retenu":"retenu","reticent":"réticent","retient":"retient","retiree":"retirée",
"retombe":"retombe","retomber":"retomber","retour":"retour","revenu":"revenu","revenus":"revenus",
"reviendrait":"reviendrait","reviews":"reviews","revision":"révision","revocable":"révocable",
"revue":"revue","risque":"risque","robuste":"robuste","robustesse":"robustesse","rupture":"rupture",
"salaire":"salaire","salaires":"salaires","salariale":"salariale","salariales":"salariales",
"sanitaire":"sanitaire","sante":"santé","scenario":"scénario","scenarios":"scénarios",
"scientifique":"scientifique","secteur":"secteur","section":"section","sectorielles":"sectorielles",
"securitaire":"sécuritaire","securite":"sécurité","selective":"sélective","sens":"sens","sept":"sept",
"septembre":"septembre","sera":"sera","serait":"serait","serieux":"sérieux","sert":"sert","services":"services",
"seuil":"seuil","seule":"seule","signale":"signalé","signe":"signe","signer":"signer","simultanee":"simultanée",
"sincerite":"sincérité","situaient":"situaient","social":"social","sociale":"sociale","sociales":"sociales",
"sociaux":"sociaux","societe":"société","societes":"sociétés","soins":"soins","solde":"solde",
"solidarite":"solidarité","solide":"solide","sondages":"sondages","sorte":"sorte","sortie":"sortie",
"sorties":"sorties","soumis":"soumis","soustraction":"soustraction","soutenabilite":"soutenabilité",
"soutenables":"soutenables","soutiennent":"soutiennent","soutient":"soutient","speciale":"spéciale",
"spectaculaire":"spectaculaire","stabilisation":"stabilisation","strategique":"stratégique",
"strategiquement":"stratégiquement","strategiques":"stratégiques","strictes":"strictes",
"structure":"structure","structurel":"structurel","structurelle":"structurelle",
"structurellement":"structurellement","subsides":"subsides","subsidiarite":"subsidiarité",
"substance":"substance","subvention":"subvention","subventions":"subventions","suffit":"suffit",
"superieur":"supérieur","superieures":"supérieures","supposait":"supposait","suppose":"suppose",
"suppression":"suppression","supprimees":"supprimées","supprimer":"supprimer","surprofits":"surprofits",
"surveillance":"surveillance","survit":"survit","survivra":"survivra","suspension":"suspension",
"symbole":"symbole","symbolique":"symbolique","syndical":"syndical","systematique":"systématique",
"systeme":"système","systemes":"systèmes","table":"table","taches":"tâches","taille":"taille",
"tard":"tard","taux":"taux","taxation":"taxation","taxe":"taxe","taxer":"taxer","taxes":"taxes",
"techniquement":"techniquement","telephones":"téléphones","temporaire":"temporaire","temps":"temps",
"tension":"tension","terme":"terme","test":"test","tester":"tester","theorique":"théorique",
"ticket":"ticket","tient":"tient","tiers":"tiers","titres":"titres","totale":"totale","touche":"touche",
"toucher":"toucher","traitement":"traitement","trajectoire":"trajectoire","tranche":"tranche",
"trancher":"trancher","transfert":"transfert","transforme":"transforme","transformer":"transformer",
"transition":"transition","transparence":"transparence","transport":"transport","travail":"travail",
"travailler":"travailler","travailleur":"travailleur","travailleurs":"travailleurs","trente":"trente",
"tres":"très","tresorerie":"trésorerie","trois":"trois","troisieme":"troisième","trophee":"trophée",
"trou":"trou","unieme":"unième","uniformement":"uniformément","uniformiser":"uniformiser",
"unique":"unique","utiles":"utiles","valeur":"valeur","valide":"validé","values":"values",
"variante":"variante","variantes":"variantes","vaut":"vaut","vehicule":"véhicule","vente":"vente",
"vers":"vers","via":"via","vident":"vident","vie":"vie","vigueur":"vigueur","vingt":"vingt",
"vingts":"vingts","virgule":"virgule","vite":"vite","voie":"voie","voiture":"voiture","voitures":"voitures",
"volet":"volet","volontairement":"volontairement","vooruit":"vooruit","vote":"voté","votee":"votée",
"vraie":"vraie","wallon":"wallon","zero":"zéro","zones":"zones",
"d'Etat":"d'État","l'Etat":"l'État","d'ecart":"d'écart","d'economie":"d'économie","d'economies":"d'économies",
"d'effectivite":"d'effectivité","d'efficacite":"d'efficacité","d'efficience":"d'efficience",
"d'epargne":"d'épargne","d'epargnants":"d'épargnants","d'hypotheses":"d'hypothèses","d'ici":"d'ici",
"d'impot":"d'impôt","d'incapacite":"d'incapacité","d'integration":"d'intégration","d'index":"d'index",
"d'inflation":"d'inflation","l'ecart":"l'écart","l'economie":"l'économie","l'elargissement":"l'élargissement",
"l'esperance":"l'espérance","l'etat":"l'état","l'evaluation":"l'évaluation","l'exoneration":"l'exonération",
"l'experience":"l'expérience","l'impot":"l'impôt","l'incapacite":"l'incapacité","l'indexation":"l'indexation",
"l'intitule":"l'intitulé","l'assumez":"l'assumez","l'aveu":"l'aveu","l'ampleur":"l'ampleur",
"qu'environ":"qu'environ","qu'exige":"qu'exige","n'existe":"n'existe","n'intervenant":"n'intervenant",
"n'intervient":"n'intervient","n'accepte":"n'accepte",
}

# Expressions qui doivent primer sur le mot a mot.
PHRASES = [
 (r"\ba regime\b", "à régime"), (r"\bA REGIME\b", "À RÉGIME"),
 (r"\ba l'horizon\b", "à l'horizon"), (r"\ba la\b", "à la"), (r"\ba un\b", "à un"), (r"\ba une\b", "à une"),
 (r"\ba ce\b", "à ce"), (r"\ba cette\b", "à cette"), (r"\ba ces\b", "à ces"), (r"\ba son\b", "à son"),
 (r"\ba leur\b", "à leur"), (r"\ba des\b", "à des"), (r"\ba deux\b", "à deux"), (r"\ba trois\b", "à trois"),
 (r"\ba cinq\b", "à cinq"), (r"\ba dix\b", "à dix"), (r"\ba vingt\b", "à vingt"), (r"\ba huit\b", "à huit"),
 (r"\ba 20\b", "à 20"), (r"\ba 2029\b", "à 2029"), (r"\ba 2031\b", "à 2031"), (r"\ba 2035\b", "à 2035"),
 (r"\ba partir\b", "à partir"), (r"\ba ecarter\b", "à écarter"), (r"\ba regle", "à règle"),
 (r"\ba nouveau\b", "à nouveau"), (r"\ba peine\b", "à peine"), (r"\ba cote\b", "à côté"),
 (r"\ba tort\b", "à tort"), (r"\ba terme\b", "à terme"), (r"\ba court\b", "à court"), (r"\ba long\b", "à long"),
 (r"\ba moyen\b", "à moyen"), (r"\ba l'", "à l'"), (r"\ba huis\b", "à huis"), (r"\ba condition\b", "à condition"),
 (r"\ba l'ordre\b", "à l'ordre"), (r"\bjusqu'a\b", "jusqu'à"), (r"\bau-dela\b", "au-delà"),
 (r"\bvis-a-vis\b", "vis-à-vis"), (r"\bdes lors\b", "dès lors"), (r"\bdes 2025\b", "dès 2025"),
 (r"\bdes mai\b", "dès mai"), (r"\bdes que\b", "dès que"), (r"\bdes l'\b", "dès l'"),
 (r"\bou que\b", "où que"), (r"\bla ou\b", "là où"), (r"\bce qui\b", "ce qui"),
 (r"\bau moment ou\b", "au moment où"), (r"\bl'ordre de\b", "l'ordre de"),
 (r"\bc'est-a-dire\b", "c'est-à-dire"), (r"\bpar rapport a\b", "par rapport à"),
 (r"\bdu\b", "du"), (r"\bplus tot\b", "plus tôt"),
]

def accentuer(t):
    for motif, rempl in PHRASES:
        t = re.sub(motif, rempl, t)
    def sub(m):
        w = m.group(0)
        if w in MOTS: return MOTS[w]
        b = w.lower()
        if b in MOTS:
            r = MOTS[b]
            return r[0].upper() + r[1:] if w[0].isupper() else r
        return w
    return re.sub(r"[A-Za-z]+(?:'[A-Za-z]+)?", sub, t)

def parcourir(o):
    if isinstance(o, str):  return accentuer(o)
    if isinstance(o, list): return [parcourir(v) for v in o]
    if isinstance(o, dict): return {k: parcourir(v) if k not in ("slug","ref","id","famille","type","delai","provenance","sensCertitude") else v for k, v in o.items()}
    return o

if __name__ == "__main__":
    for f in sys.argv[1:]:
        p = pathlib.Path(f)
        p.write_text(json.dumps(parcourir(json.loads(p.read_text())), ensure_ascii=False, indent=1), encoding="utf-8")
        print("accentue :", f)
